/* eslint-disable */
// This file is generated by frontend/scripts/gen-aurora-themes.mjs. Do not edit by hand.

export type AuroraTheme = {
  id: string;
  label: string;
  swatches: {
    background: string;
    primary: string;
    secondary: string;
    accent: string;
  };
  hasDark: boolean;
};

export const DEFAULT_AURORA_THEME_ID = "northern-light";
export const AURORA_THEME_STORAGE_KEY = "aurora-theme";

export const AURORA_THEMES: AuroraTheme[] = [
  {
    id: DEFAULT_AURORA_THEME_ID,
    label: "Northern Light",
    swatches: {
  "background": "hsl(240 9.0909% 97.8431%)",
  "primary": "hsl(139.6552 52.7273% 43.1373%)",
  "secondary": "hsl(218.5401 79.1908% 66.0784%)",
  "accent": "hsl(189.635 81.0651% 66.8627%)"
},
    hasDark: true,
  },
  {
  "id": "amber-minimal",
  "label": "Amber minimal",
  "swatches": {
    "background": "hsl(0 0% 100%)",
    "primary": "hsl(37.6923 92.1260% 50.1961%)",
    "secondary": "hsl(220.0000 14.2857% 95.8824%)",
    "accent": "hsl(48.0000 100.0000% 96.0784%)"
  },
  "hasDark": true
},
  {
  "id": "caffeine",
  "label": "Cafféine",
  "swatches": {
    "background": "hsl(0 0% 97.6471%)",
    "primary": "hsl(16.6667 21.9512% 32.1569%)",
    "secondary": "hsl(34.0541 100.0000% 85.4902%)",
    "accent": "hsl(0 0% 90.9804%)"
  },
  "hasDark": true
},
  {
  "id": "claymorphism",
  "label": "Claymorphism",
  "swatches": {
    "background": "hsl(20 5.8824% 90%)",
    "primary": "hsl(238.7324 83.5294% 66.6667%)",
    "secondary": "hsl(24.0000 5.7471% 82.9412%)",
    "accent": "hsl(292.5000 44.4444% 92.9412%)"
  },
  "hasDark": true
},
  {
  "id": "clean-state",
  "label": "Clean State",
  "swatches": {
    "background": "hsl(210.0000 40.0000% 98.0392%)",
    "primary": "hsl(238.7324 83.5294% 66.6667%)",
    "secondary": "hsl(220 13.0435% 90.9804%)",
    "accent": "hsl(226.4516 100% 93.9216%)"
  },
  "hasDark": true
},
  {
  "id": "modern-minimal",
  "label": "Modern Minimal",
  "swatches": {
    "background": "hsl(0 0% 100%)",
    "primary": "hsl(217.2193 91.2195% 59.8039%)",
    "secondary": "hsl(220.0000 14.2857% 95.8824%)",
    "accent": "hsl(204.0000 93.7500% 93.7255%)"
  },
  "hasDark": true
},
  {
  "id": "amethyst",
  "label": "Amethyst",
  "swatches": {
    "background": "hsl(260 23.0769% 97.4510%)",
    "primary": "hsl(260.4000 22.9358% 57.2549%)",
    "secondary": "hsl(258.9474 33.3333% 88.8235%)",
    "accent": "hsl(342.4615 56.5217% 77.4510%)"
  },
  "hasDark": true
},
  {
  "id": "bold-tech",
  "label": "bold Tech",
  "swatches": {
    "background": "hsl(0 0% 100%)",
    "primary": "hsl(258.3117 89.5349% 66.2745%)",
    "secondary": "hsl(252.0000 100% 97.0588%)",
    "accent": "hsl(214.2857 94.5946% 92.7451%)"
  },
  "hasDark": true
},
  {
  "id": "candyland",
  "label": "Candyland",
  "swatches": {
    "background": "hsl(200 23.0769% 97.4510%)",
    "primary": "hsl(349.5238 100% 87.6471%)",
    "secondary": "hsl(197.4000 71.4286% 72.5490%)",
    "accent": "hsl(60 100% 50%)"
  },
  "hasDark": true
},
  {
  "id": "catpuccin",
  "label": "Catpuccin",
  "swatches": {
    "background": "hsl(220.0000 23.0769% 94.9020%)",
    "primary": "hsl(266.0440 85.0467% 58.0392%)",
    "secondary": "hsl(222.8571 15.9091% 82.7451%)",
    "accent": "hsl(197.0667 96.5665% 45.6863%)"
  },
  "hasDark": true
},
  {
  "id": "claude",
  "label": "Claude",
  "swatches": {
    "background": "hsl(48 33.3333% 97.0588%)",
    "primary": "hsl(15.1111 55.5556% 52.3529%)",
    "secondary": "hsl(46.1538 22.8070% 88.8235%)",
    "accent": "hsl(46.1538 22.8070% 88.8235%)"
  },
  "hasDark": true
},
  {
  "id": "cosmic-night",
  "label": "Cosmic Night",
  "swatches": {
    "background": "hsl(240 100.0000% 98.0392%)",
    "primary": "hsl(251.9008 55.7604% 57.4510%)",
    "secondary": "hsl(249.3750 100% 93.7255%)",
    "accent": "hsl(218.4615 100.0000% 92.3529%)"
  },
  "hasDark": true
},
  {
  "id": "cyberpunk",
  "label": "Cyberpunk",
  "swatches": {
    "background": "hsl(210 16.6667% 97.6471%)",
    "primary": "hsl(312.9412 100% 50%)",
    "secondary": "hsl(240 100% 97.0588%)",
    "accent": "hsl(168 100% 50%)"
  },
  "hasDark": true
},
  {
  "id": "elegant-luxury",
  "label": "Elegant Luxury",
  "swatches": {
    "background": "hsl(0 0% 100%)",
    "primary": "hsl(21.7450 65.6388% 55.4902%)",
    "secondary": "hsl(180 17.5879% 39.0196%)",
    "accent": "hsl(0 0% 93.3333%)"
  },
  "hasDark": true
},
  {
  "id": "graphite",
  "label": "Graphite",
  "swatches": {
    "background": "hsl(0 0% 94.1176%)",
    "primary": "hsl(0 0% 37.6471%)",
    "secondary": "hsl(0 0% 87.8431%)",
    "accent": "hsl(0 0% 75.2941%)"
  },
  "hasDark": true
},
  {
  "id": "midnight-bloom",
  "label": "Midnight Bloom",
  "swatches": {
    "background": "hsl(0 0% 97.6471%)",
    "primary": "hsl(246.9065 74.3316% 63.3333%)",
    "secondary": "hsl(210.3704 75.7009% 79.0196%)",
    "accent": "hsl(72.0000 17.9283% 49.2157%)"
  },
  "hasDark": true
},
  {
  "id": "ocean-breeze",
  "label": "Ocean Breeze",
  "swatches": {
    "background": "hsl(208 100% 97.0588%)",
    "primary": "hsl(142.0859 70.5628% 45.2941%)",
    "secondary": "hsl(204.0000 93.7500% 93.7255%)",
    "accent": "hsl(149.2683 80.3922% 90.0000%)"
  },
  "hasDark": true
},
  {
  "id": "pastel-dreams",
  "label": "Pastel Dreams",
  "swatches": {
    "background": "hsl(280.0000 33.3333% 96.4706%)",
    "primary": "hsl(255.1351 91.7355% 76.2745%)",
    "secondary": "hsl(267.5676 90.2439% 91.9608%)",
    "accent": "hsl(292.5000 44.4444% 92.9412%)"
  },
  "hasDark": true
},
  {
  "id": "sage-garden",
  "label": "Sage Garden",
  "swatches": {
    "background": "hsl(45 22.2222% 96.4706%)",
    "primary": "hsl(138 8.2645% 52.5490%)",
    "secondary": "hsl(77.1429 19.6262% 79.0196%)",
    "accent": "hsl(102.8571 11.4754% 76.0784%)"
  },
  "hasDark": true
},
  {
  "id": "soft-pop",
  "label": "Soft Pop",
  "swatches": {
    "background": "hsl(80.0000 33.3333% 96.4706%)",
    "primary": "hsl(243.3962 75.3555% 58.6275%)",
    "secondary": "hsl(173.4146 80.3922% 40%)",
    "accent": "hsl(37.6923 92.1260% 50.1961%)"
  },
  "hasDark": true
},
  {
  "id": "starry-night",
  "label": "Starry Night",
  "swatches": {
    "background": "hsl(216 33.3333% 97.0588%)",
    "primary": "hsl(220.5882 46.7890% 42.7451%)",
    "secondary": "hsl(38.6364 89.1892% 70.9804%)",
    "accent": "hsl(201.6867 40.0966% 59.4118%)"
  },
  "hasDark": true
},
  {
  "id": "sunset-horizon",
  "label": "Sunset Horizon",
  "swatches": {
    "background": "hsl(24.0000 100.0000% 98.0392%)",
    "primary": "hsl(11.6250 100% 68.6275%)",
    "secondary": "hsl(8.5714 100.0000% 95.8824%)",
    "accent": "hsl(26.1069 98.4962% 73.9216%)"
  },
  "hasDark": true
},
  {
  "id": "supabase",
  "label": "Supabase",
  "swatches": {
    "background": "hsl(0 0% 98.8235%)",
    "primary": "hsl(151.3274 66.8639% 66.8627%)",
    "secondary": "hsl(0 0% 99.2157%)",
    "accent": "hsl(0 0% 92.9412%)"
  },
  "hasDark": true
},
  {
  "id": "tangerine",
  "label": "Tangerine",
  "swatches": {
    "background": "hsl(204.0000 12.1951% 91.9608%)",
    "primary": "hsl(13.2143 73.0435% 54.9020%)",
    "secondary": "hsl(220.0000 14.2857% 95.8824%)",
    "accent": "hsl(207.6923 46.4286% 89.0196%)"
  },
  "hasDark": true
},
  {
  "id": "twitter",
  "label": "Twitter",
  "swatches": {
    "background": "hsl(0 0% 100%)",
    "primary": "hsl(203.8863 88.2845% 53.1373%)",
    "secondary": "hsl(210 25% 7.8431%)",
    "accent": "hsl(211.5789 51.3514% 92.7451%)"
  },
  "hasDark": true
},
  {
  "id": "vercel",
  "label": "Vercel",
  "swatches": {
    "background": "hsl(223.8136 0.0005% 98.6829%)",
    "primary": "hsl(0 0% 0%)",
    "secondary": "hsl(223.8136 0.0001% 92.1478%)",
    "accent": "hsl(223.8136 0.0001% 92.1478%)"
  },
  "hasDark": true
},
  {
  "id": "violet-bloom",
  "label": "Violet Bloom",
  "swatches": {
    "background": "hsl(0 0% 99.2157%)",
    "primary": "hsl(257.9412 100% 60%)",
    "secondary": "hsl(214.2857 24.1379% 94.3137%)",
    "accent": "hsl(221.3793 100% 94.3137%)"
  },
  "hasDark": true
},
];
