"use client";

import * as Lucide from "lucide-react";

export * from "lucide-react";
export type { LucideIcon } from "lucide-react";

const fallbackIcon = (Lucide as any).Square ?? ((props: any) => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" {...props}>
    <rect x="4" y="4" width="16" height="16" rx="2" />
  </svg>
));

const resolveIcon = (name: string, fallbackName?: string) => {
  const direct = (Lucide as any)[name];
  if (direct) return direct;
  if (fallbackName) {
    const alt = (Lucide as any)[fallbackName];
    if (alt) return alt;
  }
  return fallbackIcon;
};

export const ArrowRightIcon = resolveIcon("ArrowRightIcon", "ArrowRight");
export const ArrowUpRightIcon = resolveIcon("ArrowUpRightIcon", "ArrowUpRight");
export const BoxesIcon = resolveIcon("BoxesIcon", "Boxes");
export const BrushCleaning = resolveIcon("BrushCleaning");
export const ChartArea = resolveIcon("ChartArea");
export const ChartBarIcon = resolveIcon("ChartBarIcon");
export const ChartCandlestick = resolveIcon("ChartCandlestick");
export const ChartNoAxesColumn = resolveIcon("ChartNoAxesColumn");
export const ChartNoAxesColumnIncreasing = resolveIcon("ChartNoAxesColumnIncreasing");
export const CheckIcon = resolveIcon("CheckIcon", "Check");
export const ChevronRightIcon = resolveIcon("ChevronRightIcon", "ChevronRight");
export const CircleArrowOutUpRight = resolveIcon("CircleArrowOutUpRight");
export const CircleArrowRight = resolveIcon("CircleArrowRight");
export const CircleCheck = resolveIcon("CircleCheck");
export const CircleCheckBig = resolveIcon("CircleCheckBig");
export const CodeXml = resolveIcon("CodeXml");
export const FlagIcon = resolveIcon("FlagIcon", "Flag");
export const GanttChartSquareIcon = resolveIcon("GanttChartSquareIcon", "GanttChartSquare");
export const HeadphonesIcon = resolveIcon("HeadphonesIcon", "Headphones");
export const HeartIcon = resolveIcon("HeartIcon", "Heart");
export const HelpCircleIcon = resolveIcon("HelpCircleIcon");
export const LineChart = resolveIcon("LineChart");
export const LucideGitGraph = resolveIcon("LucideGitGraph", "GitGraph");
export const Mail = resolveIcon("Mail");
export const Map = resolveIcon("Map");
export const MapPin = resolveIcon("MapPin");
export const Maximize2 = resolveIcon("Maximize2");
export const Medal = resolveIcon("Medal");
export const Megaphone = resolveIcon("Megaphone");
export const Menu = resolveIcon("Menu");
export const MessageCircle = resolveIcon("MessageCircle");
export const MessageCircleDashed = resolveIcon("MessageCircleDashed");
export const MessageCircleMore = resolveIcon("MessageCircleMore");
export const MessageCircleOff = resolveIcon("MessageCircleOff");
export const MessageCircleQuestion = resolveIcon("MessageCircleQuestion");
export const MessageSquare = resolveIcon("MessageSquare");
export const MessageSquareMore = resolveIcon("MessageSquareMore");
export const MessagesSquare = resolveIcon("MessagesSquare");
export const Mic = resolveIcon("Mic");
export const Minus = resolveIcon("Minus");
export const MinusIcon = resolveIcon("MinusIcon");
export const Monitor = resolveIcon("Monitor");
export const MonitorCog = resolveIcon("MonitorCog");
export const MonitorSmartphone = resolveIcon("MonitorSmartphone");
export const Moon = resolveIcon("Moon");
export const MoonStar = resolveIcon("MoonStar");
export const MousePointer2 = resolveIcon("MousePointer2");
export const MoveRight = resolveIcon("MoveRight");
export const MoveUpRight = resolveIcon("MoveUpRight");
export const Newspaper = resolveIcon("Newspaper");
export const NotebookText = resolveIcon("NotebookText");
export const Palette = resolveIcon("Palette");
export const PanelsTopLeft = resolveIcon("PanelsTopLeft");
export const Paperclip = resolveIcon("Paperclip");
export const Pause = resolveIcon("Pause");
export const PenTool = resolveIcon("PenTool");
export const PersonStanding = resolveIcon("PersonStanding");
export const Phone = resolveIcon("Phone");
export const Play = resolveIcon("Play");
export const PlayIcon = resolveIcon("PlayIcon");
export const Plug2 = resolveIcon("Plug2");
export const Plus = resolveIcon("Plus");
export const PlusCircle = resolveIcon("PlusCircle");
export const PocketKnife = resolveIcon("PocketKnife");
export const Pointer = resolveIcon("Pointer");
export const Presentation = resolveIcon("Presentation");
export const PuzzleIcon = resolveIcon("PuzzleIcon");
export const Pyramid = resolveIcon("Pyramid");
export const RadioTower = resolveIcon("RadioTower");
export const Redo = resolveIcon("Redo");
export const Repeat = resolveIcon("Repeat");
export const Rocket = resolveIcon("Rocket");
export const RocketIcon = resolveIcon("RocketIcon");
export const RotateCcw = resolveIcon("RotateCcw");
export const Scaling = resolveIcon("Scaling");
export const Scan = resolveIcon("Scan");
export const ScanFace = resolveIcon("ScanFace");
export const Scissors = resolveIcon("Scissors");
export const ScissorsLineDashed = resolveIcon("ScissorsLineDashed");
export const ScrollText = resolveIcon("ScrollText");
export const Send = resolveIcon("Send");
export const Server = resolveIcon("Server");
export const Settings = resolveIcon("Settings");
export const Settings2 = resolveIcon("Settings2");
export const Share = resolveIcon("Share");
export const Share2 = resolveIcon("Share2");
export const Shield = resolveIcon("Shield");
export const ShieldCheck = resolveIcon("ShieldCheck");
export const ShieldCheckIcon = resolveIcon("ShieldCheckIcon");
export const ShieldUser = resolveIcon("ShieldUser");
export const ShoppingBag = resolveIcon("ShoppingBag");
export const ShoppingCart = resolveIcon("ShoppingCart");
export const ShoppingCartIcon = resolveIcon("ShoppingCartIcon");
export const Slash = resolveIcon("Slash");
export const SlidersHorizontal = resolveIcon("SlidersHorizontal");
export const Smartphone = resolveIcon("Smartphone");
export const Snowflake = resolveIcon("Snowflake");
export const Sparkle = resolveIcon("Sparkle");
export const Sparkles = resolveIcon("Sparkles");
export const Square = resolveIcon("Square");
export const SquareDashedMousePointer = resolveIcon("SquareDashedMousePointer");
export const SquareKanban = resolveIcon("SquareKanban");
export const SquarePen = resolveIcon("SquarePen");
export const Star = resolveIcon("Star");
export const Subtitles = resolveIcon("Subtitles");
export const Sun = resolveIcon("Sun");
export const SwatchBook = resolveIcon("SwatchBook");
export const Tablet = resolveIcon("Tablet");
export const Target = resolveIcon("Target");
export const Terminal = resolveIcon("Terminal");
export const Text = resolveIcon("Text");
export const TextQuote = resolveIcon("TextQuote");
export const Timer = resolveIcon("Timer");
export const TrendingUp = resolveIcon("TrendingUp");
export const Trophy = resolveIcon("Trophy");
export const TrophyIcon = resolveIcon("TrophyIcon");
export const Twitter = resolveIcon("Twitter");
export const Type = resolveIcon("Type");
export const Upload = resolveIcon("Upload");
export const User = resolveIcon("User");
export const UserIcon = resolveIcon("UserIcon");
export const UserPen = resolveIcon("UserPen");
export const Users = resolveIcon("Users");
export const UsersRound = resolveIcon("UsersRound");
export const Video = resolveIcon("Video");
export const View = resolveIcon("View");
export const Volume2 = resolveIcon("Volume2");
export const Wallet = resolveIcon("Wallet");
export const Wand = resolveIcon("Wand");
export const WandSparkles = resolveIcon("WandSparkles");
export const Wifi = resolveIcon("Wifi");
export const Workflow = resolveIcon("Workflow");
export const Wrench = resolveIcon("Wrench");
export const X = resolveIcon("X");
export const XCircle = resolveIcon("XCircle");
export const Zap = resolveIcon("Zap");
export const ZoomIn = resolveIcon("ZoomIn");
